import Shashlik from "./foods-image/shashlik";
import Salatlar from "./foods-image/salatlar";
import SamarqandOsh from "./foods-image/samarqand-osh";
import MilliyTaomlar from "./foods-image/milliy-taomlar";
import YevropaTaomlari from "./foods-image/yevropa-taomlari";
import Ichimliklar from "./foods-image/ichimliklar";
import BirinchiTaomlar from "./foods-image/birinchi-taomlar";
const {
  chuchvara,
  turkshorva,
  mastava,
  shorva,
  suplapsha,
  yashilkaram,
  salyonka,
} = BirinchiTaomlar;
const {
  shashlik10,
  shashlik5,
  beshpanja,
  pamidorshashlik,
  shashlikmoloty,
  shashlikmolotycharvi,
  shashlikmolotykichkina,
  shashliknapaleon,
  shashlikrulet,
} = Shashlik;
const {
  baqlajon,
  gnezdogluxarya,
  guruziya,
  kapriz,
  tayskiy,
  tovuqbnsezan,
  vitaminlar,
  yangiyunsalat,
  achhiq,
  alivie,
  arugulabnsalat,
  bahorguldastasi,
  bek,
  fransuzcha,
  gribnoy,
  lesnoybor,
  monastirskaya,
  mujskayaradost,
  nejnost,
  qovoqcha,
  qoyningtili,
  qoziqornolivie,
  risalka,
  sayor,
  smak,
  tatibkorvazn,
  tbilisi,
  victoriya,
  vitamin,
  yunoncha,
} = Salatlar;
const {
  achichuk,
  anzur,
  bahorsalat,
  marinat,
  salyonny,
  samarqandosh7,
  samarqandoshbutun,
  turp,
} = SamarqandOsh;
const {
  chaxoxbili,
  dolma,
  jizsamarqand,
  jizumakay,
  qozichoqq,
  qozichoqy,
  qozonkabob,
  vaguri,
} = MilliyTaomlar;
const {
  balonezapastasi,
  gabyadina,
  goshtsay,
  kolbaski,
  ziqorinligosht,
  sabzavotbnmedalyon,
  sachkabob,
  sachtova,
} = YevropaTaomlari;
const {
  ananaslisok1,
  chortoq,
  cola,
  pepsi,
  fanta,
  olchalisok1,
  olmalisok1,
  pamidorlisok1,
  sprite,
  suv,
} = Ichimliklar;
export const foods = [
  {
    id: 1,
    title: "Birinchi taomlar",
    link: "birinchi-taomlar",
    props: [
      {
        id: 1,
        title: "Chuchvara",
        price: "24 150 so'm",
        url: chuchvara,
      },
      {
        id: 2,
        title: "Tovuq Sho'rva",
        price: "16 100 so'm",
        url: suplapsha,
      },
      {
        id: 3,
        title: "Mastava",
        price: "27 600 so'm",
        url: mastava,
      },
      {
        id: 4,
        title: "Sho'rva",
        price: "29 900 so'm",
        url: shorva,
      },
      {
        id: 5,
        title: "Sup-Lapsha s Frikadelkami",
        price: "18 400 so'm",
        url: suplapsha,
      },
      {
        id: 6,
        title: "Turkcha Sho'rva",
        price: "24 150 so'm",
        url: turkshorva,
      },
      {
        id: 7,
        title: "Yashil Karom Sho'rva",
        price: "28 750 so'm",
        url: yashilkaram,
      },
      {
        id: 8,
        title: "Shi zelyonniy s frikadelkami",
        price: "29 900 so'm",
        url: "https://vkusno-i-prosto.ru/wp-content/uploads/2012/07/shhi-s-frikadelkami.jpg",
      },
      {
        id: 9,
        title: "Sup chechivitsi",
        price: "26 450 so'm",
        url: "https://i.ytimg.com/vi/uiR9Q5m8NMs/mqdefault.jpg",
      },
      {
        id: 10,
        title: "Xash",
        price: "44 850 so'm",
        url: "https://i.ytimg.com/vi/6KYCcH-8L18/maxresdefault.jpg",
      },
      {
        id: 11,
        title: "Solyanka",
        price: "35 650 so'm",
        url: salyonka,
      },
      {
        id: 12,
        title: "Bo'rsh",
        price: "28 750 so'm",
        url: "https://zira.uz/wp-content/uploads/2018/11/borw-3-1.jpg",
      },
    ],
  },
  {
    id: 2,
    title: "Shashlik",
    link: "shashlik",
    props: [
      {
        id: 1,
        title: "Shashlik Assorti Katta 10 kishilik",
        price: "633 650 so'm",
        url: shashlik10,
      },
      {
        id: 2,
        title: "Shashlik Assorti Kichkina 5 kishilik",
        price: "331 200 so'm",
        url: shashlik5,
      },
      {
        id: 3,
        title: "Besh panja qo'zichoq",
        price: "95 450 so'm",
        url: beshpanja,
      },
      {
        id: 4,
        title: "'Besh Panja' mol go'shti",
        price: "116 150 so'm",
        url: beshpanja,
      },
      {
        id: 5,
        title: "Pomidor Shashlik",
        price: "4 600 so'm",
        url: pamidorshashlik,
      },
      {
        id: 6,
        title: "Shashlik Moloty",
        price: "40 250 so'm",
        url: shashlikmoloty,
      },
      {
        id: 7,
        title: "Shashlik Moloty charvi",
        price: "56 350 so'm",
        url: shashlikmolotycharvi,
      },
      {
        id: 8,
        title: "Shashlik Moloty kichkina",
        price: "25 300 so'm",
        url: shashlikmolotykichkina,
      },
      {
        id: 9,
        title: "Shashlik Napoleon",
        price: "52 900 so'm",
        url: shashliknapaleon,
      },
      {
        id: 10,
        title: "Shashlik Rulet",
        price: "54 050 so'm",
        url: shashlikrulet,
      },
      {
        id: 11,
        title: "Qo'zichq bolagi",
        price: "47 150 so'm",
        url: "",
      },
      {
        id: 13,
        title: "Qo'zichoq qovurg'alari",
        price: "70 150 so'm",
        url: "https://extra-sugar.ru/uploads/pypthumb-nux-722x587.jpg",
      },
      {
        id: 14,
        title: "Qo'zi beli",
        price: "87 400 so'm",
        url: "",
      },
      {
        id: 15,
        title: "Kavkaz Qo'zisi",
        price: "94 300 so'm",
        url: "https://zira.uz/wp-content/uploads/2020/02/baranina-zapechennaya-v-gorchice.jpg",
      },
      {
        id: 16,
        title: "Tovuq Oyoqlari",
        price: "39 100 so'm",
        url: "https://daryo.uz/cache/2022/02/photo_2022-02-21_23-28-01-1280x640.jpg",
      },
      {
        id: 17,
        title: "Tovuq Qanotlari",
        price: "34 500 so'm",
        url: "https://zira.uz/wp-content/uploads/2020/05/krylyshki_v_medovo_soevom_marinade_s_kukuruzoy_2.jpg",
      },
      {
        id: 18,
        title: "Tovuq Golen",
        price: "52 900 so'm",
        url: "https://yukber.uz/image/cache/catalog/product/YK0350/YK0350-700x700.jpg",
      },
      {
        id: 19,
        title: "Mol go'shti bo'lagi",
        price: "56 350 so'm",
        url: "https://zira.uz/wp-content/uploads/2021/02/gestollo_govyadina_tushenaya_v_souse_sacebeli_2.jpg",
      },
      {
        id: 20,
        title: "Mol go'sht bo'lagi kichkina",
        price: "28 750 so'm",
        url: "https://zira.uz/wp-content/uploads/2021/02/gestollo_govyadina_tushenaya_v_souse_sacebeli_2.jpg",
      },
    ],
  },
  {
    id: 3,
    title: "Salatlar",
    link: "salatlar",
    props: [
      {
        id: 1,
        title: "Baqlajonlik",
        price: "23 000 so'm",
        url: baqlajon,
      },
      {
        id: 2,
        title: "Gnezdo Gluxarya",
        price: "36 800 so'm",
        url: gnezdogluxarya,
      },
      {
        id: 3,
        title: "Gruziya",
        price: "33 350 so'm",
        url: guruziya,
      },
      {
        id: 4,
        title: "Kapriz",
        price: "75 900 so'm",
        url: kapriz,
      },
      {
        id: 5,
        title: "Tayskiy",
        price: "40 250 so'm",
        url: tayskiy,
      },
      {
        id: 6,
        title: "Tovuq bilan Sezar",
        price: "51 750 so'm",
        url: tovuqbnsezan,
      },
      {
        id: 7,
        title: "Vitaminlar To'plami",
        price: "36 800 so'm",
        url: vitaminlar,
      },
      {
        id: 8,
        title: "Yangi Yunoncha Salat",
        price: "58 650 so'm",
        url: yangiyunsalat,
      },
      {
        id: 9,
        title: "Yunoncha",
        price: "34 500 so'm",
        url: yunoncha,
      },
      {
        id: 10,
        title: "Tatib ko'r va Vazn yo'qot",
        price: "35 650 so'm",
        url: tatibkorvazn,
      },
      {
        id: 11,
        title: "Arugula bilan salat",
        price: "36 800 so'm",
        url: arugulabnsalat,
      },
      {
        id: 12,
        title: "Vitaminlar",
        price: "36 800 so'm",
        url: vitamin,
      },
      {
        id: 13,
        title: "Smak",
        price: "24 150 so'm",
        url: smak,
      },
      {
        id: 14,
        title: "idil",
        price: "28 750 so'm",
        url: "https://altynachar.com/mtk44/43-thickbox_default/sezar-salat.jpg",
      },
      {
        id: 15,
        title: "Bahor guldastasi",
        price: "27 600 so'm",
        url: bahorguldastasi,
      },
      {
        id: 16,
        title: "Qovoqcha",
        price: "19 550 so'm",
        url: qovoqcha,
      },
      {
        id: 17,
        title: "Qo'ziqorin Olivie",
        price: "31 050 so'm",
        url: qoziqornolivie,
      },
      {
        id: 18,
        title: "Lesnoy Bor",
        price: "26 450 so'm",
        url: lesnoybor,
      },
      {
        id: 19,
        title: "Nejnost",
        price: "35 650 so'm",
        url: nejnost,
      },
      {
        id: 20,
        title: "Gribnoy chudo",
        price: "34 500 so'm",
        url: gribnoy,
      },
      {
        id: 21,
        title: "Rusalka",
        price: "50 600 so'm",
        url: risalka,
      },
      {
        id: 22,
        title: "Sayor",
        price: "29 900 so'm",
        url: sayor,
      },
      {
        id: 23,
        title: "Olivie",
        price: "26 450 so'm",
        url: alivie,
      },
      {
        id: 24,
        title: "Monastirskaya Izba",
        price: "58 650 so'm",
        url: monastirskaya,
      },
      {
        id: 25,
        title: "Qo'yning Tili",
        price: "35 650 so'm",
        url: qoyningtili,
      },
      {
        id: 26,
        title: "Fransuzcha",
        price: "26 450 so'm",
        url: fransuzcha,
      },
      {
        id: 27,
        title: "Mujskaya radost",
        price: "66 700 so'm",
        url: mujskayaradost,
      },
      {
        id: 28,
        title: "Achсhiq",
        price: "43 700 so'm",
        url: achhiq,
      },
      {
        id: 29,
        title: "Vdohnoveniy",
        price: "51 750 so'm",
        url: "",
      },
      {
        id: 30,
        title: "Viktoriya",
        price: "44 850 so'm",
        url: victoriya,
      },
      {
        id: 31,
        title: "Bek",
        price: "54 050 so'm",
        url: bek,
      },
      {
        id: 32,
        title: "Tbilisi",
        price: "37 950 so'm",
        url: tbilisi,
      },
      {
        id: 33,
        title: "Selyodka shuba",
        price: "29 900 so'm",
        url: "https://i0.wp.com/cdn.lifehacker.ru/wp-content/uploads/2018/12/shutterstock_510916834_1576580260-e1576580280189-1600x800.jpg",
      },
      {
        id: 34,
        title: "Selyodka krestyansky",
        price: "40 250 so'm",
        url: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Selyodka_pod_Shuboy_at_White_Nights%2C_Beijing_%2820201023130349%29.jpg",
      },
      {
        id: 35,
        title: "Mimoza",
        price: "29 900 so'm",
        url: "https://zira.uz/wp-content/uploads/2019/11/mimoza.jpg",
      },
      {
        id: 36,
        title: "Chakka",
        price: "11 500 so'm",
        url: "https://www.restoran-shafran.uz/image/cache/catalog/product/salati/chakka-750x500.jpg",
      },
      {
        id: 37,
        title: "Limon",
        price: "11 500 so'm",
        url: "https://zira.uz/wp-content/uploads/2021/04/salat-s-ogurcami-i-brynzoy-3.jpg",
      },
      {
        id: 38,
        title:
          "https://zira.uz/wp-content/uploads/2019/06/salat-meksikanskiy.jpg",
        price: "41 400 so'm",
        url: "",
      },
      {
        id: 39,
        title: "Teshinskiy Tili",
        price: "18 400 so'm",
        url: "https://cdn.cakelab.uz/products/thumbs/1_1643830607.jpg",
      },
      {
        id: 40,
        title: "Biryuzoviy zelyonim",
        price: "29 900 so'm",
        url: "https://play-lh.googleusercontent.com/QhFGUoGcF53W_ls55LTjpU2xSRoyPI2_v0GSyBzac7RrBsUqzdM_Fkvn9sYAaic8HA",
      },
    ],
  },
  {
    id: 4,
    title: "Samarqand Osh",
    link: "samarqand-osh",
    props: [
      {
        id: 1,
        title: "Samarqand Osh Butun",
        price: "42 550 so'm",
        url: samarqandoshbutun,
      },
      {
        id: 2,
        title: "Samarqand Osh 0.7",
        price: "39 100 so'm",
        url: samarqandosh7,
      },
      {
        id: 3,
        title: "Bahor Salat",
        price: "11 500 so'm",
        url: bahorsalat,
      },
      {
        id: 4,
        title: "Marinat",
        price: "11 500 so'm",
        url: marinat,
      },
      {
        id: 5,
        title: "Salyonny",
        price: "11 500 so'm",
        url: salyonny,
      },
      {
        id: 6,
        title: "Turp Chakka",
        price: "11 500 so'm",
        url: turp,
      },
      {
        id: 7,
        title: "Achichuk",
        price: "12 650 so'm",
        url: achichuk,
      },
      {
        id: 8,
        title: "Anzur",
        price: "14 950 so'm",
        url: anzur,
      },
    ],
  },
  {
    id: 5,
    title: "Milliy taomlar",
    link: "milliy-taomlar",
    props: [
      {
        id: 1,
        title: "Chaxoxbili",
        price: "81 650 so'm",
        url: chaxoxbili,
      },
      {
        id: 2,
        title: "Dolma",
        price: "54 050 so'm",
        url: dolma,
      },
      {
        id: 3,
        title: "Jiz Samarqand",
        price: "184 000 so'm",
        url: jizsamarqand,
      },
      {
        id: 4,
        title: "Jiz Umakay",
        price: "78 200 so'm",
        url: jizumakay,
      },
      {
        id: 5,
        title: "Qo'zichoq Qovurg'asi",
        price: "142 600 so'm",
        url: qozichoqq,
      },
      {
        id: 6,
        title: "Qo'zichoq Yelkasi",
        price: "473 800 so'm",
        url: qozichoqy,
      },
      {
        id: 7,
        title: "Qozon Kabob",
        price: "96 600 so'm",
        url: qozonkabob,
      },
      {
        id: 8,
        title: "Vaguri",
        price: "133 400 so'm",
        url: vaguri,
      },
    ],
  },
  {
    id: 6,
    title: "Yevropa taomlari",
    link: "yevropa-taomlari",
    props: [
      {
        id: 1,
        title: "Baloneza Pastasi",
        price: "58 650 so'm",
        url: balonezapastasi,
      },
      {
        id: 2,
        title: "Govyadina po-domashnemu",
        price: "56 350 so'm",
        url: gabyadina,
      },
      {
        id: 3,
        title: "Go'sht Say",
        price: "75 900 so'm",
        url: goshtsay,
      },
      {
        id: 4,
        title: "Kolbaski",
        price: "92 000 so'm",
        url: kolbaski,
      },
      {
        id: 5,
        title: "Qo'ziqorinli Go'sht",
        price: "89 700 so'm",
        url: ziqorinligosht,
      },
      {
        id: 6,
        title: "Sabzavotlar bilan medalyon",
        price: "103 500 so'm",
        url: sabzavotbnmedalyon,
      },
      {
        id: 7,
        title: "Sach Kabob",
        price: "108 100 so'm",
        url: sachkabob,
      },
      {
        id: 8,
        title: "Sach Tava",
        price: "64 400 so'm",
        url: sachtova,
      },
    ],
  },
  {
    id: 7,
    title: "Ichimliklar",
    link: "ichimliklar",
    props: [
      {
        id: 1,
        title: "Вода 1,5",
        price: "5 350 so'm",
        url: suv,
      },
      {
        id: 2,
        title: "Спрайт 1.5",
        price: "20 700 so'm",
        url: sprite,
      },
      {
        id: 3,
        title: "Фанта 1.5",
        price: "20 700 so'm",
        url: fanta,
      },
      {
        id: 4,
        title: "Coca-Cola 1.5L",
        price: "20 700 so'm",
        url: cola,
      },
      {
        id: 5,
        title: "Сок Яблоко 'Соч.долина' 1л",
        price: "20 700 so'm",
        url: olmalisok1,
      },
      {
        id: 6,
        title: "Сок Вишня 'Соч.долина' 1л",
        price: "20 700 so'm",
        url: olchalisok1,
      },
      {
        id: 7,
        title: "Сок Мулти 'Соч.долина' 1л",
        price: "20 700 so'm",
        url: ananaslisok1,
      },
      {
        id: 8,
        title: "Сок Томат 'Соч.долина' 1л",
        price: "20 700 so'm",
        url: pamidorlisok1,
      },
      {
        id: 9,
        title: "Чорток 0.5",
        price: "11 500 so'm",
        url: chortoq,
      },
      {
        id: 10,
        title: "Pepsi 1.5L",
        price: "20 700 so'm",
        url: pepsi,
      },
    ],
  },
];
